---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dotpng
  namespace: default
  labels:
    app: dotpng
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dotpng
  template:
    metadata:
      labels:
        app: dotpng
        version: '0'
      annotations:
        atomist.com/repo-image: '[{"repo":{"owner":"satellite-of-love","name":"dotpng"},"image":"jessitron/dotpng"}]'
    spec:
      containers:
      - name: dotpng
        image: jessitron/dotpng:0.2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: ATOMIST_CONFIG_PATH
          value: /opt/atm/client.config.json
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/"
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 30
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: "/"
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        resources:
          limits:
            cpu: 1.0
            memory: 1024Mi
          requests:
            cpu: 0.1
            memory: 768Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
